name: Engrish CI

on: 
  push: 
    branches: 
      - master
      - in-app-updates

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java environment
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    - name: Get the flutter packages
    - run: flutter pub get
    - name: Format the app files
    - run: flutter format .
    - name: Analyze the app files for error checking
    - run: flutter analyze .
    - name: Enter the android directory
    - run: cd android/
    - name: Create the encrypted keystore file
    - run: echo "${{ secrets.KEYSTORE }}" > release.jks.asc
    - name: Decrypt the keystore file
    - run: gpg -d --passphrase "${{ secrets.PASS_PHRASE }}" --batch release.jks.asc > release.jks
    - name: Expand key info
    - run: echo "${{ secrets.KEYSTORE_PASS }}" > key.properties
    - name: Exit android directory
    - run: cd ..
    - name: Build the android app
    - run: flutter build apk --split-per-abi
    - name: Upload arm64-v8a-release
    - uses: actions/upload-artifact@v1
      with: 
        name: arm64-v8a-release
        path: build\app\outputs\apk\release\app-arm64-v8a-release.apk
    - name: Upload armeabi-v7a-release
    - uses: actions/upload-artifact@v1
      with:
        name: armeabi-v7a-release
        path: build\app\outputs\apk\release\app-armeabi-v7a-release.apk
    - name: Upload x86_64-release
    - uses: actions/upload-artifact@v1
      with:
        name: x86_64-release
        path: build\app\outputs\apk\release\app-x86_64-release.apk
