name: Engrish CI

on: 
  push: 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    - name: Prepare packages
      run: flutter pub get
    - name: Error checking
      run: flutter format .
           flutter analyze .
    - name: Keystore expansion
      if:   github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
           cd android/
           echo "${{ secrets.KEYSTORE }}" > release.jks.asc
           gpg -d --passphrase "${{ secrets.PASS_PHRASE }}" --batch release.jks.asc > app/release.jks
           echo "${{ secrets.KEYSTORE_PASS }}" > key.properties
           cd ..
    - name: App build
      if:   github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: flutter build apk --split-per-abi
    - name: Change built names
      if:   github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
          cd build/app/outputs/apk/release/
          mv app-arm64-v8a-release.apk engrish_arm64.apk
          mv app-armeabi-v7a-release.apk engrish_arm7.apk
          mv app-x86_64-release.apk engrish_x86.apk
          rm -rf app-arm64-v8a-release.apk
          rm -rf app-armeabi-v7a-release.apk
          rm -rf app-x86_64-release.apk
    - name: Upload release
      if:   github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v1
      with: 
        name: Engrish_Release
        path: build/app/outputs/apk/release/
