name: Engrish CI

on: 
  push: 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Environment setup
      uses: actions/checkout@v1
            actions/setup-java@v1
            subosito/flutter-action@v1
        java-version: '12.x'
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    - name: Prepare packages
      run: flutter pub get
    - name: Error checking
      run: flutter format .
           flutter analyze .
    - name: Keystore expansion
      run: cd android/
           echo "${{ secrets.KEYSTORE }}" > release.jks.asc
           gpg -d --passphrase "${{ secrets.PASS_PHRASE }}" --batch release.jks.asc > release.jks
           echo "${{ secrets.KEYSTORE_PASS }}" > key.properties
           cd ..
    - name: App build
      run: flutter build apk --split-per-abi
    - name: Upload arm64
      uses: actions/upload-artifact@v1
      with: 
        name: arm64-v8a-release
        path: build\app\outputs\apk\release\app-arm64-v8a-release.apk
    - name: Upload armv7a
      uses: actions/upload-artifact@v1
      with:
        name: armeabi-v7a-release
        path: build\app\outputs\apk\release\app-armeabi-v7a-release.apk
    - name: Upload x86_64
      uses: actions/upload-artifact@v1
      with:
        name: x86_64-release
        path: build\app\outputs\apk\release\app-x86_64-release.apk
